
services:
  portfolio-client:
    build: 
      context: .
      dockerfile: dockerfile
    ports:
      - "3001:5173"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules 